### ISSUE TITLE
Where is this chart published?

### ISSUE THREAD

**Issue by waldner** [casdoor/casdoor-helm#23]
The instructions in the docs are wrong (https://casdoor.org/docs/basic/try-with-helm/), after some messing around I discovered that the published version on oci://registry-1.docker.io/casbin/casdoor-helm-charts is 0.4.5, which however is very different from what's published here.

**Comment by hsluoyz** [comment]
@sp71  @MichaelSp

**Comment by sp71** [comment]
The latest tag for [charts](https://hub.docker.com/r/casbin/casdoor-helm-charts/tags) as of today is v1.604.0.  The [document](https://casdoor.org/docs/basic/try-with-helm/) currently references 1.524.0 which isn't too far away from the document.

**Comment by hsluoyz** [comment]
@waldner see docs: https://casdoor.org/docs/basic/try-with-helm/#step-1-install-the-casdoor-chart

```
helm install casdoor oci://registry-1.docker.io/casbin/casdoor-helm-charts --version 1.604.0
```

**Comment by waldner** [comment]
```
helm fetch oci://registry-1.docker.io/casbin/casdoor-helm-charts --version 1.604.0
Error: registry-1.docker.io/casbin/casdoor-helm-charts:1.604.0: not found
```

**Comment by hsluoyz** [comment]
@sp71
