### ISSUE TITLE
can not connect with crunchy db 

### ISSUE THREAD

**Issue by Meet-S0ni** [casdoor/casdoor-helm#24]
kubectl logs -f pod/casdoor-58f45c79f4-shv9z -n casdoor
panic: pq: no pg_hba.conf entry for host "10.224.0.76", user "postgres", database "postgres", no encryption

goroutine 1 [running]:
github.com/casdoor/casdoor/object.(*Ormer).createTable(0xc0008d7000)
        /go/src/casdoor/object/ormer.go:293 +0xaa5
github.com/casdoor/casdoor/object.CreateTables()
        /go/src/casdoor/object/ormer.go:114 +0x3a
main.main()
        /go/src/casdoor/main.go:36 +0x35
        
 Thanks you for help
 https://access.crunchydata.com/documentation/postgres-operator/4.4.0/advanced/custom-configuration/

**Comment by hsluoyz** [comment]
@sp71  @MichaelSp

**Comment by hsluoyz** [comment]
@Meet-S0ni it seems that the `postgres` user from IP: `10.224.0.76` is not allowed to access your cloud DB. Should it should be resolved on your side.
