### ISSUE TITLE
Add InitContainers capacity.

### ISSUE THREAD

**Issue by ArKam** [casdoor/casdoor-helm#26]
Hi folks!

Could we add the ability for a deployment to set an initContainer?
That would help with some storage provider that need to change the access right on volumes before starting the container that mount it. That would allow for an automated process as currently you either need to override the deployment part or do it manually before binding an extra volume.

PS: I could add that in the deployment template and create a PR.

Thanks in advance!

**Comment by hsluoyz** [comment]
@ArKam can you make a PR to support it?
