### ISSUE TITLE
Add index.yaml

### ISSUE THREAD

**Issue by sp71** [casdoor/casdoor-helm#5]
The index.yaml is missing from the repository. It [originally](https://github.com/casbin/casdoor/commit/86dea71efdbef2b165fc0212769e3fd2fc37fbee) existed in casdoor but was removed once the helm components were migrated to this repo. The index.yaml is an important file as it simplifies the helm installation process for developers without needing to manually download the helm chart to their machines. We should add this file back in and similar to how Chart.yaml is updated by the [CI](https://github.com/casbin/casdoor/blob/master/.github/workflows/build.yml#L231), the index.yaml should also be updated accordingly. Currently, this [workflow](https://github.com/casdoor/casdoor-helm/blob/master/.github/workflows/helm.yml#L40) generates the index.yaml but it's never committed to git. A quick solution would be to update casdoor [workflow](https://github.com/casbin/casdoor/blob/master/.github/workflows/build.yml#L231) to commit the index.yaml and push up to docker hub. This repo would no longer require a workflow directory then

**Comment by sp71** [comment]
@MichaelSp

**Comment by MichaelSp** [comment]
AFAIK `index.yaml` is not required in OCI based repos: https://helm.sh/docs/topics/registries/#migrating-from-chart-repos

**Comment by sp71** [comment]
It's good to offer the option at a minimum. For example, the terraform [provider](https://github.com/hashicorp/terraform-provider-helm) for helm expects it
