### ISSUE TITLE
Error Pulling Helm Repo

### ISSUE THREAD

**Issue by Hemant0601** [casdoor/casdoor-helm#7]
Getting below error while pulling up the helm repo

`helm repo add casdoor https://hub.docker.com/repository/docker/casbin/casdoor-helm-charts
`

`[ec2-user@ip-10-101-6-41 casdoor]$ helm repo add casdoor https://hub.docker.com/repository/docker/casbin/casdoor-helm-charts
Error: looks like "https://hub.docker.com/repository/docker/casbin/casdoor-helm-charts" is not a valid chart repository or cannot be reached: error converting YAML to JSON: yaml: line 21: mapping values are not allowed in this context
`

**Comment by hsluoyz** [comment]
@sp71 @MichaelSp can you help fix this?

**Comment by MichaelSp** [comment]
As I said [here](https://github.com/casbin/casdoor/pull/2587#issuecomment-1880144253)

>  * the proposed helm repo add casdoor https://hub.docker.com/repository/docker/casbin/casdoor-helm-charts did not work for me. Use commands from https://hub.docker.com/layers/casbin/casdoor-helm-charts/0.4.0/images/sha256-de878a2843964f2913e32b8d28a0e9ef8728e16da309ebb987389047cd32f0dd?context=explore instead

**Comment by hsluoyz** [comment]
@MichaelSp it seems that the docs: https://casdoor.org/docs/basic/try-with-helm/ is wrong, can you fix the docs?

BTW, how did this link:  https://hub.docker.com/layers/casbin/casdoor-helm-charts/0.4.0/images/sha256-de878a2843964f2913e32b8d28a0e9ef8728e16da309ebb987389047cd32f0dd?context=explore come out? I didn't think it's good as it's so strange.

**Comment by hsluoyz** [comment]
@Hemant0601 docs updated: https://casdoor.org/docs/basic/try-with-helm/

Try:

![image](https://github.com/casdoor/casdoor-helm/assets/3787410/542e115f-0892-43bc-806c-7bce94f8b48c)

**Comment by Hemant0601** [comment]
@hsluoyz 

I am still getting below issue

`hemantkumar@MacBook-Pro-3 Documents % sudo helm pull casdoor oci://registry-1.docker.io/casbin/casdoor-helm-charts --version 0.4.3 --untar
Password:
Error: non-absolute URLs should be in form of repo_name/path_to_chart, got: casdoor
hemantkumar@MacBook-Pro-3 Documents % 
`

**Comment by hsluoyz** [comment]
@Hemant0601 can you try `helm install casdoor oci://registry-1.docker.io/casbin/casdoor-helm-charts --version 1.502.0` ?

**Comment by cshields** [comment]
their docs are missing the "v" in the beginning of their version tags. This would work instead:

`helm install casdoor oci://registry-1.docker.io/casbin/casdoor-helm-charts --version v1.659.0`

**Comment by hsluoyz** [comment]
@cshields is that true? Can you fix the docs?

**Comment by Hemant0601** [comment]
Hi, 
Are the docs updated?

**Comment by hsluoyz** [comment]
@Hemant0601 fixed in: https://github.com/casdoor/casdoor-website/commit/0342ec8ee0418b211c0927878524d015a9e21af0
