### ISSUE TITLE
bug: the casbin-bot committer is not correct

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-helm#8]
The committer in this repo is wrong: https://github.com/casdoor/casdoor-helm/commits/master/

Why wrong?

- No avatar
- No link

![image](https://github.com/casdoor/casdoor-helm/assets/3787410/6272d64c-18ac-4987-b196-3c1529193757)

The correct example is: https://github.com/casdoor/casdoor.github.io/commits/master/

![image](https://github.com/casdoor/casdoor-helm/assets/3787410/c6684925-0bda-4778-991c-212d15dfbce1)

**Comment by hsluoyz** [comment]
@sp71 @MichaelSp can you help fix this?

**Comment by sp71** [comment]
It might be the git config is missing the secrets.GH_BOT_TOKEN before it pushes. Not 100% sure tho.

**Comment by hsluoyz** [comment]
@sp71 the Email is wrong. Fixed by: https://github.com/casbin/casdoor/commit/60096468fe8ef61a666447d4919eecc3bd52ea1d

**Comment by sp71** [comment]
Thought this [issue](https://github.com/orgs/community/discussions/26560) would have been a hindrance. Glad it's fixed.
